services:
  - type: web
    name: vibe-trading-crypto-bridge
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn crypto_webhook_bridge:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: WEBHOOK_PASSCODE
        value: MY_SECRET_PASSCODE
      - key: TELEGRAM_BOT_TOKEN
        value: "8720752006:AAFAJTuacGL3BncmGftAaR5jaOnXj_SIpek"
      - key: TELEGRAM_CHAT_ID
        value: "1580412709"
      - key: PORT
        value: 8000

  - type: web
    name: vibe-trading-fxopen-bridge
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn fxopen_bridge:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: WEBHOOK_PASSCODE
        value: MY_SECRET_PASSCODE
      - key: TELEGRAM_BOT_TOKEN
        value: "8720752006:AAFAJTuacGL3BncmGftAaR5jaOnXj_SIpek"
      - key: TELEGRAM_CHAT_ID
        value: "1580412709"
      - key: PORT
        value: 8000

